<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaBlogPost extends BaseaBlogPost
{
  public function getPermalink()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers('Url');

    return url_for('a_blog_post', $this, false);
  }
}