<?php

/**
 * PluginaBlogCategoryGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaBlogCategoryGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaBlogCategoryGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaBlogCategoryGroup');
    }
}