<?php

/**
 * PluginaEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEventTable extends aBlogItemTable
{
  protected $categoryColumn = 'events';
    
  /**
   * Returns an instance of this class.
   *
   * @return object PluginaEventTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginaEvent');
  }
}