<?php

/**
 * PluginaBlogItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginaBlogItem extends BaseaBlogItem
{  
  /**
   * These date methods are use in the routing of the permalink
   */
  public function getYear()
  {
    return date('Y', strtotime($this->getPublishedAt()));
  }

  public function getMonth()
  {
    return date('m', strtotime($this->getPublishedAt()));
  }

  public function getDay()
  {
    return date('d', strtotime($this->getPublishedAt()));
  }
  
  public function getFeedSlug()
  {
    return $this->slug;
  }
  
  public function postInsert($event)
  {
    $page = new aPage();
    $page['slug'] = 'aBlog-'.$this['id'];
    $page->save();
    $slot = $page->createSlot('aRichText');
    $slot->value = 'This is your body.';
    $slot->save();
    $page->newAreaVersion('body', 'add', 
      array(
        'permid' => 1, 
        'slot' => $slot));
    $this->Page = $page;
    $this->slug = 'untitled-'.$this['id'];
    $this->title = 'untitled';
    $this->save();
  }
  
  public function postDelete($event)
  {
    $this->Page->delete();
  }
  
  public function getFeedText()
  {
    $text = '';
    foreach($this->Page->getArea('body') as $slot)
    {
      if(method_exists($slot, 'getSearchText'))
      {
        $text .= $slot->getSearchText();
      }
    }
    return $text;
  }
}