<?php

/**
 * PluginaBlogSlotSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaBlogSlotSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaBlogSlotSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaBlogSlotSlot');
    }
}