<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaBlogEvent extends BaseaBlogEvent
{
  public function getPermalink()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers('Url');
    
    return url_for('a_calendar_post', $this, false);
  }
  
  public function getStartDateTime()
  {
    return strtotime($this->getStartDate() .' '. $this->getStartTime());
  }
  
  public function getYear()
  {
    return date('Y', strtotime($this->getStartDate()));
  }

  public function getMonth()
  {
    return date('m', strtotime($this->getStartDate()));
  }

  public function getDay()
  {
    return date('d', strtotime($this->getStartDate()));
  }
}